Repository xmos/vocalfusion-rpi-setup, pull requests merged in 2023-02, with the labels that each got.

#56 Add version of clock tool which allows arbitrary clock setting
  CHANGELOG.md
  resources/clk_dac_setup/Makefile
  resources/clk_dac_setup/setup_mclk_bclk.c
Labels: type:testing

#58 Feature/3800 disable mclk default
  CHANGELOG.md
  README.md
  resources/clk_dac_setup/setup_io_exp_and_dac.py
Labels: type:enhancement

#59 fix indentation
  resources/clk_dac_setup/setup_io_exp_and_dac.py
Labels: type:enhancement

#60 Typo in comment about MCLK
  CHANGELOG.md
  README.md
  resources/clk_dac_setup/Makefile
  resources/clk_dac_setup/setup_io_exp_and_dac.py
  resources/clk_dac_setup/setup_mclk_bclk.c
  setup.sh
Labels: type:documentation
